version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app.js:/app.js
    restart: always

  ftp:
    image: stilliard/pure-ftpd
    ports:
      - 21:21
      - 30000-30009:30000-30009
    volumes:
      - ./:/home/ftpuser/
    environment:
      - FTP_USER=root
      - FTP_PASS=toor