version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app.js:/app.js
    restart: always

  ftp:
    image: stilliard/pure-ftpd
    ports:
      - 21:21
      - 30000-30009:30000-30009
    command: bash /run.sh
    volumes:
      - ./:/home/admin
    environment:
      - FTP_USER=admin
      - FTP_USER_NAME= admin
      - FTP_PASS=admin
      - FTP_USER_HOME= /home/admin
      - FTP_USER_UID= 33
      - FTP_USER_GID= 33
      - PUBLICHOST= 192.168.195.130
      